plugins {
    id 'com.android.application'
}

android {
    namespace 'com.photo'
    compileSdk 34

    defaultConfig {
        applicationId "com.photo"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "photo.apk"
        }
    }
}
